#!/bin/bash

sudo apt update && sudo apt install git fonts-powerline wget lm-sensors -y

#-------------------------
# Installing Miniconda
#-------------------------
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
bash ~/miniconda.sh -b -p $HOME/miniconda
export PATH="$HOME/miniconda/bin:$PATH"
conda init

cat .condarc >> $HOME/.condarc

#-------------------------
# Pre-install for R
#-------------------------
sudo apt install --no-install-recommends software-properties-common dirmngr
wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc
sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
sudo apt update

#-------------------------
# Install R base, dev, some libs for R
#-------------------------
sudo apt install --no-install-recommends r-base -y
sudo apt install r-base-dev libxml2-dev libcurl4-openssl-dev libssl-dev -y

#-------------------------
# Install prompter
#-------------------------
# Create the directory inside .config for the shell configs
mkdir -p $HOME/.config/gr8sh/
cp prompt.* $HOME/.config/gr8sh/

# Paste the if statement to be ran everytime bash is called a.k.a. .bashrc
cat .bashrc >> $HOME/.bashrc

source ~/.bashrc